apiVersion: v1
kind: Pod
metadata:
  name: cpu-memory-stress
  namespace: monitoring
  labels:
    app: cpu-memory-stress
spec:
  containers:
  - name: cpu-memory-stress
    image: ubuntu:20.04
    command: ["bash", "-c"]
    args:
      - |
        apt update && apt install -y stress; \
        echo "Starting intermittent CPU and memory stress..."; \
        while true; do \
          echo "Stressing..."; \
          stress --cpu 2 --vm 2 --vm-bytes 64M --timeout 60s; \
          echo "Cooling down..."; \
          sleep 300; \
        done
  restartPolicy: Always
