apiVersion: v1
kind: Pod
metadata:
  name: disk-stress
  namespace: monitoring
  labels:
    app: disk-stress
spec:
  containers:
  - name: disk-writer
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        echo "Starting disk write stress..."; \
        while true; do dd if=/dev/zero of=/data/testfile bs=1M count=100; sync; sleep 2; done
    volumeMounts:
    - mountPath: /data
      name: temp-volume
  restartPolicy: Always
  volumes:
  - name: temp-volume
    emptyDir: {}
