apiVersion: v1
kind: Pod
metadata:
  name: busybox-log-generator
  namespace: monitoring
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - /bin/sh
        - -c
        - >
          while true; do
            echo "$(date) INFO: Simulated log entry for Kubernetes at $(hostname)";
            sleep 1;
          done
      resources:
        limits:
          cpu: 50m
          memory: 32Mi
