apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
    <source>
      @type forward
      port 24231
    </source>

    <match **>
      @type file
      path /fluentd/logs/all_logs
      append true
    </match>
